// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataGateway_GetConfig_FullMethodName   = "/datuplet.gateway.v2.DataGateway/GetConfig"
	DataGateway_Shutdown_FullMethodName    = "/datuplet.gateway.v2.DataGateway/Shutdown"
	DataGateway_OpenWriter_FullMethodName  = "/datuplet.gateway.v2.DataGateway/OpenWriter"
	DataGateway_WriteChunk_FullMethodName  = "/datuplet.gateway.v2.DataGateway/WriteChunk"
	DataGateway_CloseWriter_FullMethodName = "/datuplet.gateway.v2.DataGateway/CloseWriter"
	DataGateway_OpenReader_FullMethodName  = "/datuplet.gateway.v2.DataGateway/OpenReader"
	DataGateway_ReadChunk_FullMethodName   = "/datuplet.gateway.v2.DataGateway/ReadChunk"
	DataGateway_CloseReader_FullMethodName = "/datuplet.gateway.v2.DataGateway/CloseReader"
	DataGateway_Commit_FullMethodName      = "/datuplet.gateway.v2.DataGateway/Commit"
	DataGateway_GetSchema_FullMethodName   = "/datuplet.gateway.v2.DataGateway/GetSchema"
	DataGateway_GetSample_FullMethodName   = "/datuplet.gateway.v2.DataGateway/GetSample"
	DataGateway_Log_FullMethodName         = "/datuplet.gateway.v2.DataGateway/Log"
)

// DataGatewayClient is the client API for DataGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataGateway is the v2 gRPC service that components use to access the data lake.
// This version supports bucket-based access, format conversion, transformations, and optimized Parquet output.
//
// Key concepts:
// - Tables are identified as bucket.table (e.g., "raw.orders")
// - Components declare bucket-level access (read or write)
// - Tables can be created dynamically under authorized buckets
// - SDK uses: WriteChunk(table, data) or WriteChunkToBucket(bucket, table, data)
type DataGatewayClient interface {
	// Lifecycle
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ComponentConfig, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// Writing (component -> storage)
	// For defaultBucket mode: OpenWriter with table name only
	// For explicit mode: OpenWriterToBucket with bucket + table
	OpenWriter(ctx context.Context, in *OpenWriterRequest, opts ...grpc.CallOption) (*OpenWriterResponse, error)
	WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	CloseWriter(ctx context.Context, in *CloseWriterRequest, opts ...grpc.CallOption) (*CloseWriterResponse, error)
	// Reading (storage -> component)
	// Always explicit: OpenReader with bucket + table
	OpenReader(ctx context.Context, in *OpenReaderRequest, opts ...grpc.CallOption) (*OpenReaderResponse, error)
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	CloseReader(ctx context.Context, in *CloseReaderRequest, opts ...grpc.CallOption) (*CloseReaderResponse, error)
	// Commit
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// Schema/Sampling (for discovery)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
	GetSample(ctx context.Context, in *GetSampleRequest, opts ...grpc.CallOption) (*SampleResponse, error)
	// Logging
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type dataGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGatewayClient(cc grpc.ClientConnInterface) DataGatewayClient {
	return &dataGatewayClient{cc}
}

func (c *dataGatewayClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ComponentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentConfig)
	err := c.cc.Invoke(ctx, DataGateway_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, DataGateway_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) OpenWriter(ctx context.Context, in *OpenWriterRequest, opts ...grpc.CallOption) (*OpenWriterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenWriterResponse)
	err := c.cc.Invoke(ctx, DataGateway_OpenWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, DataGateway_WriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) CloseWriter(ctx context.Context, in *CloseWriterRequest, opts ...grpc.CallOption) (*CloseWriterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseWriterResponse)
	err := c.cc.Invoke(ctx, DataGateway_CloseWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) OpenReader(ctx context.Context, in *OpenReaderRequest, opts ...grpc.CallOption) (*OpenReaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenReaderResponse)
	err := c.cc.Invoke(ctx, DataGateway_OpenReader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataGateway_ServiceDesc.Streams[0], DataGateway_ReadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadChunkRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataGateway_ReadChunkClient = grpc.ServerStreamingClient[DataChunk]

func (c *dataGatewayClient) CloseReader(ctx context.Context, in *CloseReaderRequest, opts ...grpc.CallOption) (*CloseReaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseReaderResponse)
	err := c.cc.Invoke(ctx, DataGateway_CloseReader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, DataGateway_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, DataGateway_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) GetSample(ctx context.Context, in *GetSampleRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, DataGateway_GetSample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGatewayClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, DataGateway_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGatewayServer is the server API for DataGateway service.
// All implementations must embed UnimplementedDataGatewayServer
// for forward compatibility.
//
// DataGateway is the v2 gRPC service that components use to access the data lake.
// This version supports bucket-based access, format conversion, transformations, and optimized Parquet output.
//
// Key concepts:
// - Tables are identified as bucket.table (e.g., "raw.orders")
// - Components declare bucket-level access (read or write)
// - Tables can be created dynamically under authorized buckets
// - SDK uses: WriteChunk(table, data) or WriteChunkToBucket(bucket, table, data)
type DataGatewayServer interface {
	// Lifecycle
	GetConfig(context.Context, *GetConfigRequest) (*ComponentConfig, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// Writing (component -> storage)
	// For defaultBucket mode: OpenWriter with table name only
	// For explicit mode: OpenWriterToBucket with bucket + table
	OpenWriter(context.Context, *OpenWriterRequest) (*OpenWriterResponse, error)
	WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	CloseWriter(context.Context, *CloseWriterRequest) (*CloseWriterResponse, error)
	// Reading (storage -> component)
	// Always explicit: OpenReader with bucket + table
	OpenReader(context.Context, *OpenReaderRequest) (*OpenReaderResponse, error)
	ReadChunk(*ReadChunkRequest, grpc.ServerStreamingServer[DataChunk]) error
	CloseReader(context.Context, *CloseReaderRequest) (*CloseReaderResponse, error)
	// Commit
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// Schema/Sampling (for discovery)
	GetSchema(context.Context, *GetSchemaRequest) (*SchemaResponse, error)
	GetSample(context.Context, *GetSampleRequest) (*SampleResponse, error)
	// Logging
	Log(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedDataGatewayServer()
}

// UnimplementedDataGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataGatewayServer struct{}

func (UnimplementedDataGatewayServer) GetConfig(context.Context, *GetConfigRequest) (*ComponentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedDataGatewayServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDataGatewayServer) OpenWriter(context.Context, *OpenWriterRequest) (*OpenWriterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenWriter not implemented")
}
func (UnimplementedDataGatewayServer) WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedDataGatewayServer) CloseWriter(context.Context, *CloseWriterRequest) (*CloseWriterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseWriter not implemented")
}
func (UnimplementedDataGatewayServer) OpenReader(context.Context, *OpenReaderRequest) (*OpenReaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenReader not implemented")
}
func (UnimplementedDataGatewayServer) ReadChunk(*ReadChunkRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedDataGatewayServer) CloseReader(context.Context, *CloseReaderRequest) (*CloseReaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseReader not implemented")
}
func (UnimplementedDataGatewayServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedDataGatewayServer) GetSchema(context.Context, *GetSchemaRequest) (*SchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedDataGatewayServer) GetSample(context.Context, *GetSampleRequest) (*SampleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSample not implemented")
}
func (UnimplementedDataGatewayServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedDataGatewayServer) mustEmbedUnimplementedDataGatewayServer() {}
func (UnimplementedDataGatewayServer) testEmbeddedByValue()                     {}

// UnsafeDataGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGatewayServer will
// result in compilation errors.
type UnsafeDataGatewayServer interface {
	mustEmbedUnimplementedDataGatewayServer()
}

func RegisterDataGatewayServer(s grpc.ServiceRegistrar, srv DataGatewayServer) {
	// If the following call panics, it indicates UnimplementedDataGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataGateway_ServiceDesc, srv)
}

func _DataGateway_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_OpenWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).OpenWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_OpenWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).OpenWriter(ctx, req.(*OpenWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_WriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).WriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_WriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).WriteChunk(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_CloseWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).CloseWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_CloseWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).CloseWriter(ctx, req.(*CloseWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_OpenReader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).OpenReader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_OpenReader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).OpenReader(ctx, req.(*OpenReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_ReadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataGatewayServer).ReadChunk(m, &grpc.GenericServerStream[ReadChunkRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataGateway_ReadChunkServer = grpc.ServerStreamingServer[DataChunk]

func _DataGateway_CloseReader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).CloseReader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_CloseReader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).CloseReader(ctx, req.(*CloseReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_GetSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).GetSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_GetSample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).GetSample(ctx, req.(*GetSampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGateway_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGatewayServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGateway_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGatewayServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGateway_ServiceDesc is the grpc.ServiceDesc for DataGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datuplet.gateway.v2.DataGateway",
	HandlerType: (*DataGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _DataGateway_GetConfig_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DataGateway_Shutdown_Handler,
		},
		{
			MethodName: "OpenWriter",
			Handler:    _DataGateway_OpenWriter_Handler,
		},
		{
			MethodName: "WriteChunk",
			Handler:    _DataGateway_WriteChunk_Handler,
		},
		{
			MethodName: "CloseWriter",
			Handler:    _DataGateway_CloseWriter_Handler,
		},
		{
			MethodName: "OpenReader",
			Handler:    _DataGateway_OpenReader_Handler,
		},
		{
			MethodName: "CloseReader",
			Handler:    _DataGateway_CloseReader_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _DataGateway_Commit_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _DataGateway_GetSchema_Handler,
		},
		{
			MethodName: "GetSample",
			Handler:    _DataGateway_GetSample_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _DataGateway_Log_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadChunk",
			Handler:       _DataGateway_ReadChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
