# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gateway.v2 import gateway_pb2 as gateway_dot_v2_dot_gateway__pb2


class DataGatewayStub(object):
    """DataGateway is the v2 gRPC service that components use to access the data lake.
    This version supports format conversion, transformations, and optimized Parquet output.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/GetConfig',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.ComponentConfig.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/Shutdown',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.ShutdownResponse.FromString,
                )
        self.OpenWriter = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/OpenWriter',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.OpenWriterRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.OpenWriterResponse.FromString,
                )
        self.WriteChunk = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/WriteChunk',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.WriteChunkRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.WriteChunkResponse.FromString,
                )
        self.CloseWriter = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/CloseWriter',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.CloseWriterRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.CloseWriterResponse.FromString,
                )
        self.OpenReader = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/OpenReader',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.OpenReaderRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.OpenReaderResponse.FromString,
                )
        self.ReadChunk = channel.unary_stream(
                '/datuplet.gateway.v2.DataGateway/ReadChunk',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.ReadChunkRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.DataChunk.FromString,
                )
        self.CloseReader = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/CloseReader',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.CloseReaderRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.CloseReaderResponse.FromString,
                )
        self.Commit = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/Commit',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.CommitRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.CommitResponse.FromString,
                )
        self.GetSchema = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/GetSchema',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.SchemaResponse.FromString,
                )
        self.GetSample = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/GetSample',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.GetSampleRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.SampleResponse.FromString,
                )
        self.Log = channel.unary_unary(
                '/datuplet.gateway.v2.DataGateway/Log',
                request_serializer=gateway_dot_v2_dot_gateway__pb2.LogRequest.SerializeToString,
                response_deserializer=gateway_dot_v2_dot_gateway__pb2.LogResponse.FromString,
                )
